autoware_zmq_capnp_bridge_node:
  ros__parameters:
    capnp_dir: "/home/carpc/Software/saurabh/priuspilot/cereal/"  # ← replace with actual path
    publish_rate_hz: 35.0
    openpilot_auto_reenable_timeout: 5.0
